### ISSUE TITLE
Possible issue in umontreal.ssj.functionfit.BSpline

### ISSUE THREAD

**Issue by EXPEkmajewski** [umontreal-simul/ssj#2]
We have identified a possible issue in umontreal.ssj.functionfit.BSpline. 
We are not sure if it is in fact a bug in SSJ, or if we are using SSJ incorrectly. 
We have created the following GitHub repo to describe the issue in detail and show how to reproduce it:

https://github.com/EXPEkmajewski/ssj-issue

Thanks for taking a look!

**Comment by chwyean** [comment]
Hi there,
We will take a look at it.

**Comment by chwyean** [comment]
Just to let you know that we're working on it. There is indeed a bug in the implementation of the approximation.

**Comment by EXPEkmajewski** [comment]
Good to know, thanks!

**Comment by chwyean** [comment]
We corrected the bug in the code source. Here's the difference. The green line is from the corrected function. 
![newgraph](https://cloud.githubusercontent.com/assets/15200507/20778448/afc434b8-b73b-11e6-8c03-eb84c07e07b9.jpeg)
We also made the bisection more robust by checking the bounds before starting the search.
The master branch has been updated. I still have to upload the new package to Maven central.
Thanks for the bug report!

**Comment by EXPEkmajewski** [comment]
Thanks! I tried your hotfix with my test code (https://github.com/EXPEkmajewski/ssj-issue) and the results are very promising. It's a nice Christmas present for me :)

Are you guys planning to release this any time soon? It would make it easier for us to run SSJ in production if the latest version was available via Maven Central.

Thanks again for addressing the issue and sorry for the slow reply,

-krzys

**Comment by chwyean** [comment]
The bug fix was added previously in Pull #3, so I'm closing this issue.

**Comment by chwyean** [comment]
Hi @EXPEkmajewski,
Just to tell you that we have released SSJ 3.2.1 with the bug fixes on Maven Central.
